### PR TITLE
Add Resx file handling

### PR DESCRIPTION
**Pull request by laurentkempe**
Apply same sorting idea to resx file

### CODE REVIEW

**Comment by HowardvanRooijen** [comment]
Thanks very much Laurent! If you can ping me your address - we have some endjin swag for contributors!

**Comment by laurentkempe** [comment]
That's nice!

Here it is:

Laurent Kempé
15 rue d'Eguisheim
68110 Illzach
France

On Tue, Oct 27, 2015 at 1:37 PM, Howard van Rooijen <
notifications@github.com> wrote:

> Thanks very much Laurent! If you can ping me your address - we have some
> endjin swag for contributors!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/endjin/git-hooks/pull/10#issuecomment-151478474>.
>



-- 
Laurent Kempé - laurent.kempe@techheadbrothers.com
Jobping <http://www.jobping.com>- Advertises opportunities for Microsoft
professionals
Tech Head Brothers <http://www.TechHeadBrothers.com> - French .Net portal
Blog <http://www.laurentkempe.com> - One of the Tech Head Brothers
Microsoft ASP.NET MVP
<https://mvp.support.microsoft.com/profile/Laurent.Kempé>

**Comment by laurentkempe** [comment]
Where should I ping you?

**Comment by HowardvanRooijen** [comment]
that's fine! We're just waiting for our new swag to get delivered, then we'll post something to you

**Pull request merged**
